# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ljtheta2_cpp <- function(z, tau) {
    .Call(`_jacobi_ljtheta2_cpp`, z, tau)
}

jtheta2_cpp <- function(z, tau) {
    .Call(`_jacobi_jtheta2_cpp`, z, tau)
}

ljtheta1_cpp <- function(z, tau) {
    .Call(`_jacobi_ljtheta1_cpp`, z, tau)
}

jtheta1_cpp <- function(z, tau) {
    .Call(`_jacobi_jtheta1_cpp`, z, tau)
}

ljtheta3_cpp <- function(z, tau) {
    .Call(`_jacobi_ljtheta3_cpp`, z, tau)
}

jtheta3_cpp <- function(z, tau) {
    .Call(`_jacobi_jtheta3_cpp`, z, tau)
}

ljtheta4_cpp <- function(z, tau) {
    .Call(`_jacobi_ljtheta4_cpp`, z, tau)
}

jtheta4_cpp <- function(z, tau) {
    .Call(`_jacobi_jtheta4_cpp`, z, tau)
}

Image_eta <- function(x, gamma, t) {
    .Call(`_jacobi_Image_eta`, x, gamma, t)
}

Image_E4 <- function(x, gamma, t) {
    .Call(`_jacobi_Image_E4`, x, gamma, t)
}

Image_E6 <- function(x, gamma, t) {
    .Call(`_jacobi_Image_E6`, x, gamma, t)
}

Image_lambda <- function(x, gamma, t) {
    .Call(`_jacobi_Image_lambda`, x, gamma, t)
}

