# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

altjtheta1 <- function(z, tau) {
    .Call(`_jacobi_altjtheta1`, z, tau)
}

theta1dash <- function(z, tau) {
    .Call(`_jacobi_theta1dash`, z, tau)
}

ljtheta2_cpp <- function(z, tau) {
    .Call(`_jacobi_ljtheta2_cpp`, z, tau)
}

jtheta2_cpp <- function(z, tau) {
    .Call(`_jacobi_jtheta2_cpp`, z, tau)
}

ljtheta1_cpp <- function(z, tau) {
    .Call(`_jacobi_ljtheta1_cpp`, z, tau)
}

jtheta1_cpp <- function(z, tau) {
    .Call(`_jacobi_jtheta1_cpp`, z, tau)
}

ljtheta3_cpp <- function(z, tau) {
    .Call(`_jacobi_ljtheta3_cpp`, z, tau)
}

jtheta3_cpp <- function(z, tau) {
    .Call(`_jacobi_jtheta3_cpp`, z, tau)
}

ljtheta4_cpp <- function(z, tau) {
    .Call(`_jacobi_ljtheta4_cpp`, z, tau)
}

jtheta4_cpp <- function(z, tau) {
    .Call(`_jacobi_jtheta4_cpp`, z, tau)
}

dlogjtheta1 <- function(z, q) {
    .Call(`_jacobi_dlogjtheta1`, z, q)
}

JTheta1 <- function(z0, dalet) {
    .Call(`_jacobi_JTheta1`, z0, dalet)
}

JTheta2 <- function(z0, dalet) {
    .Call(`_jacobi_JTheta2`, z0, dalet)
}

JTheta3 <- function(z0, dalet) {
    .Call(`_jacobi_JTheta3`, z0, dalet)
}

JTheta4 <- function(z0, dalet) {
    .Call(`_jacobi_JTheta4`, z0, dalet)
}

LJTheta1 <- function(z0, dalet) {
    .Call(`_jacobi_LJTheta1`, z0, dalet)
}

LJTheta2 <- function(z0, dalet) {
    .Call(`_jacobi_LJTheta2`, z0, dalet)
}

LJTheta3 <- function(z0, dalet) {
    .Call(`_jacobi_LJTheta3`, z0, dalet)
}

LJTheta4 <- function(z0, dalet) {
    .Call(`_jacobi_LJTheta4`, z0, dalet)
}

dLTheta1 <- function(z0, dalet) {
    .Call(`_jacobi_dLTheta1`, z0, dalet)
}

lambda_cpp <- function(Dalet) {
    .Call(`_jacobi_lambda_cpp`, Dalet)
}

lambda_transfo <- function(Dalet) {
    .Call(`_jacobi_lambda_transfo`, Dalet)
}

ColorMap1 <- function(Z) {
    .Call(`_jacobi_ColorMap1`, Z)
}

Image_eta <- function(x, gamma, t) {
    .Call(`_jacobi_Image_eta`, x, gamma, t)
}

Image_E4 <- function(x, gamma, t) {
    .Call(`_jacobi_Image_E4`, x, gamma, t)
}

Image_E6 <- function(x, gamma, t) {
    .Call(`_jacobi_Image_E6`, x, gamma, t)
}

Image_lambda <- function(x, gamma, t) {
    .Call(`_jacobi_Image_lambda`, x, gamma, t)
}

