# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

modulo <- function(a, p) {
    .Call(`_jacobi_modulo`, a, p)
}

ljtheta2_cpp <- function(z, tau) {
    .Call(`_jacobi_ljtheta2_cpp`, z, tau)
}

jtheta2_cpp <- function(z, tau) {
    .Call(`_jacobi_jtheta2_cpp`, z, tau)
}

ljtheta1_cpp <- function(z, tau) {
    .Call(`_jacobi_ljtheta1_cpp`, z, tau)
}

jtheta1_cpp <- function(z, tau) {
    .Call(`_jacobi_jtheta1_cpp`, z, tau)
}

ljtheta3_cpp <- function(z, tau) {
    .Call(`_jacobi_ljtheta3_cpp`, z, tau)
}

jtheta3_cpp <- function(z, tau) {
    .Call(`_jacobi_jtheta3_cpp`, z, tau)
}

ljtheta4_cpp <- function(z, tau) {
    .Call(`_jacobi_ljtheta4_cpp`, z, tau)
}

jtheta4_cpp <- function(z, tau) {
    .Call(`_jacobi_jtheta4_cpp`, z, tau)
}

